import type { PreferenceDimensionDef } from "../types";

/**
 * Single source of truth for preference dimensions used by quiz UI,
 * personalized ranking, and explanations.
 */
export const PREFERENCE_DIMENSIONS: readonly PreferenceDimensionDef[] = [
  {
    id: "socialAtmosphere",
    label: "Social atmosphere",
    description: "How lively and social the hall tends to be.",
    category: "atmosphere",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["socialVibe"],
    defaultImportance: 2,
    explanations: {
      positive: "Matches your preference for a social atmosphere",
      negative: "Less social than you prefer",
      unknown: "Social atmosphere is unknown",
    },
  },
  {
    id: "quietAtmosphere",
    label: "Quiet atmosphere",
    description: "How quiet and calm the hall tends to be.",
    category: "atmosphere",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["quietVibe"],
    defaultImportance: 2,
    explanations: {
      positive: "Matches your preference for a quieter atmosphere",
      negative: "Louder / less quiet than you prefer",
      unknown: "Quiet vibe is unknown",
    },
  },
  {
    id: "roomSpaciousness",
    label: "Room spaciousness",
    description: "How spacious rooms feel relative to typical halls.",
    category: "room",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["spaciousnessRating", "roomSpaciousness"],
    defaultImportance: 2,
    explanations: {
      positive: "Rooms are relatively spacious",
      negative: "Rooms tend to feel smaller",
      unknown: "Room size / spaciousness is unknown",
    },
  },
  {
    id: "privacy",
    label: "Privacy",
    description: "Overall privacy of living arrangements.",
    category: "room",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["privacyRating"],
    defaultImportance: 2,
    explanations: {
      positive: "Offers good privacy",
      negative: "Lower privacy than you prefer",
      unknown: "Privacy rating is unknown",
    },
  },
  {
    id: "bathroomPrivacy",
    label: "Bathroom privacy",
    description: "How private bathrooms are (derived from style and ratings).",
    category: "bathroom",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["bathroomStyle", "privacyRating"],
    defaultImportance: 2,
    explanations: {
      positive: "Bathroom setup supports privacy",
      negative: "Bathroom setup is less private",
      unknown: "Bathroom privacy cannot be assessed",
    },
  },
  {
    id: "privateBathroom",
    label: "Private bathroom",
    description: "In-room / private bathroom.",
    category: "bathroom",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["bathroomStyle", "hasPrivateBathroom"],
    defaultImportance: 0,
    explanations: {
      positive: "Has a private bathroom",
      negative: "Does not have a private bathroom",
      unknown: "Private bathroom availability is unknown",
    },
  },
  {
    id: "suiteBathroom",
    label: "Suite bathroom",
    description: "Bathroom shared within a suite.",
    category: "bathroom",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["bathroomStyle", "hasSuiteBathroom"],
    defaultImportance: 0,
    explanations: {
      positive: "Has a suite-style bathroom",
      negative: "Does not have a suite bathroom",
      unknown: "Suite bathroom availability is unknown",
    },
  },
  {
    id: "communalBathroomOk",
    label: "Communal bathroom OK",
    description: "Comfortable with floor / communal bathrooms.",
    category: "bathroom",
    controlType: "toggle",
    scoringMode: "boolean_match",
    supportsHardConstraint: false,
    evidenceFields: ["bathroomStyle", "hasCommunalBathroom"],
    defaultImportance: 0,
    explanations: {
      positive: "Communal bathroom matches what you accept",
      negative: "Not a communal bathroom setup",
      unknown: "Bathroom style is unknown",
    },
  },
  {
    id: "roomTypeSingle",
    label: "Single room",
    description: "Access to single (one-person) rooms.",
    category: "room",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["hasSingle", "roomTypes"],
    defaultImportance: 0,
    explanations: {
      positive: "Offers single rooms",
      negative: "No single rooms available",
      unknown: "Single room availability is unknown",
    },
  },
  {
    id: "roomTypeDouble",
    label: "Double room",
    description: "Traditional double rooms.",
    category: "room",
    controlType: "toggle",
    scoringMode: "boolean_match",
    supportsHardConstraint: false,
    evidenceFields: ["hasDouble", "roomTypes"],
    defaultImportance: 0,
    explanations: {
      positive: "Offers double rooms",
      negative: "No double rooms listed",
      unknown: "Double room availability is unknown",
    },
  },
  {
    id: "suiteStyle",
    label: "Suite-style living",
    description: "Suite-style residence halls.",
    category: "building",
    controlType: "importance",
    scoringMode: "categorical",
    supportsHardConstraint: false,
    evidenceFields: ["dormType"],
    preferredCategories: ["SUITE", "suite"],
    defaultImportance: 0,
    explanations: {
      positive: "Suite-style living",
      negative: "Not suite-style",
      unknown: "Housing style is unknown",
    },
  },
  {
    id: "apartmentStyle",
    label: "Apartment-style living",
    description: "Apartment or townhouse independence.",
    category: "building",
    controlType: "importance",
    scoringMode: "categorical",
    supportsHardConstraint: false,
    evidenceFields: ["dormType"],
    preferredCategories: ["APARTMENT", "TOWNHOUSE", "apartment", "townhouse"],
    defaultImportance: 0,
    explanations: {
      positive: "Apartment-style independence",
      negative: "Not apartment-style",
      unknown: "Housing style is unknown",
    },
  },
  {
    id: "corridorStyle",
    label: "Corridor / traditional hall",
    description: "Classic corridor-style residence hall.",
    category: "building",
    controlType: "importance",
    scoringMode: "categorical",
    supportsHardConstraint: false,
    evidenceFields: ["dormType"],
    preferredCategories: ["RESIDENCE_HALL", "residence_hall", "MIXED", "FRESHMAN_ONLY"],
    defaultImportance: 0,
    explanations: {
      positive: "Traditional corridor-style hall",
      negative: "Not a traditional corridor hall",
      unknown: "Housing style is unknown",
    },
  },
  {
    id: "renovatedNewer",
    label: "Renovated / newer building",
    description: "Recently renovated or newer construction.",
    category: "building",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["renovationYear", "buildingAge", "isRenovated"],
    defaultImportance: 1,
    explanations: {
      positive: "Newer or recently renovated",
      negative: "Older building / not recently renovated",
      unknown: "Building age / renovation status is unknown",
    },
  },
  {
    id: "cleanliness",
    label: "Cleanliness",
    description: "Reported cleanliness of the hall.",
    category: "amenities",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["cleanlinessRating"],
    defaultImportance: 2,
    explanations: {
      positive: "Rated as clean",
      negative: "Cleanliness rated lower",
      unknown: "Cleanliness is unknown",
    },
  },
  {
    id: "airConditioning",
    label: "Air conditioning",
    description: "Building has air conditioning.",
    category: "amenities",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["hasAC"],
    defaultImportance: 2,
    explanations: {
      positive: "Has air conditioning",
      negative: "No air conditioning",
      unknown: "AC availability is unknown",
    },
  },
  {
    id: "naturalLight",
    label: "Natural light",
    description: "Rooms get good natural light.",
    category: "room",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["naturalLightRating"],
    defaultImportance: 1,
    explanations: {
      positive: "Good natural light",
      negative: "Limited natural light",
      unknown: "Natural light is unknown",
    },
  },
  {
    id: "storage",
    label: "Storage",
    description: "In-room and building storage options.",
    category: "room",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["storageRating", "hasStorage"],
    defaultImportance: 1,
    explanations: {
      positive: "Decent storage options",
      negative: "Limited storage",
      unknown: "Storage options are unknown",
    },
  },
  {
    id: "studyEnvironment",
    label: "Study environment",
    description: "Quiet study spaces and study-friendly vibe.",
    category: "amenities",
    controlType: "importance",
    scoringMode: "boolean_match",
    supportsHardConstraint: false,
    evidenceFields: ["studyLounges", "quietVibe"],
    defaultImportance: 2,
    explanations: {
      positive: "Supports studying (lounges / quieter vibe)",
      negative: "Weaker study environment signals",
      unknown: "Study environment is unknown",
    },
  },
  {
    id: "commonLounges",
    label: "Common lounges",
    description: "Shared lounge / common spaces.",
    category: "amenities",
    controlType: "importance",
    scoringMode: "boolean_match",
    supportsHardConstraint: false,
    evidenceFields: ["studyLounges", "hasLounge", "amenityFlags"],
    defaultImportance: 1,
    explanations: {
      positive: "Has common lounges",
      negative: "No lounge access listed",
      unknown: "Lounge availability is unknown",
    },
  },
  {
    id: "kitchens",
    label: "Kitchen access",
    description: "Kitchen or cooking access in the building.",
    category: "amenities",
    controlType: "importance",
    scoringMode: "boolean_match",
    supportsHardConstraint: false,
    evidenceFields: ["kitchenAccess"],
    defaultImportance: 1,
    explanations: {
      positive: "Kitchen access available",
      negative: "No kitchen access listed",
      unknown: "Kitchen access is unknown",
    },
  },
  {
    id: "laundry",
    label: "Laundry",
    description: "In-building laundry access.",
    category: "amenities",
    controlType: "importance",
    scoringMode: "boolean_match",
    supportsHardConstraint: false,
    evidenceFields: ["laundryAccess"],
    defaultImportance: 2,
    explanations: {
      positive: "Laundry access in building",
      negative: "No laundry access listed",
      unknown: "Laundry access is unknown",
    },
  },
  {
    id: "buildingAmenities",
    label: "Building amenities",
    description: "Overall amenity richness (count / variety).",
    category: "amenities",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["amenityCount"],
    defaultImportance: 1,
    explanations: {
      positive: "Strong amenity set",
      negative: "Fewer amenities",
      unknown: "Amenity details are unknown",
    },
  },
  {
    id: "freshmanFriendly",
    label: "Freshman-friendly",
    description: "Open to and suitable for first-year students.",
    category: "eligibility",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["freshmanEligible"],
    defaultImportance: 0,
    explanations: {
      positive: "Freshman-eligible",
      negative: "Not freshman-eligible",
      unknown: "Freshman eligibility is unknown",
    },
  },
  {
    id: "upperclassFriendly",
    label: "Upperclass-friendly",
    description: "Open to upperclass students.",
    category: "eligibility",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["upperclassEligible"],
    defaultImportance: 0,
    explanations: {
      positive: "Upperclass-eligible",
      negative: "Not upperclass-eligible",
      unknown: "Upperclass eligibility is unknown",
    },
  },
  {
    id: "communityAtmosphere",
    label: "Community atmosphere",
    description: "Sense of community in the hall.",
    category: "community",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["communityRating", "socialVibe"],
    defaultImportance: 1,
    explanations: {
      positive: "Strong community feel",
      negative: "Weaker community signals",
      unknown: "Community atmosphere is unknown",
    },
  },
  {
    id: "livingLearning",
    label: "Living-learning / themed",
    description: "Living-learning community, honors, or themed housing.",
    category: "community",
    controlType: "toggle",
    scoringMode: "boolean_match",
    supportsHardConstraint: false,
    evidenceFields: ["honorsHousing", "themedHousing", "isLivingLearning"],
    defaultImportance: 0,
    explanations: {
      positive: "Living-learning or themed community",
      negative: "Not a themed / LLC hall",
      unknown: "Themed housing status is unknown",
    },
  },
  {
    id: "genderInclusive",
    label: "Gender-inclusive",
    description: "Gender-inclusive housing options.",
    category: "community",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["genderInclusive"],
    defaultImportance: 0,
    explanations: {
      positive: "Gender-inclusive housing",
      negative: "Not listed as gender-inclusive",
      unknown: "Gender-inclusive status is unknown",
    },
  },
  {
    id: "substanceFree",
    label: "Substance-free",
    description: "Substance-free housing community.",
    category: "community",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["substanceFree", "isSubstanceFree"],
    defaultImportance: 0,
    explanations: {
      positive: "Substance-free community",
      negative: "Not substance-free",
      unknown: "Substance-free status is unknown",
    },
  },
  {
    id: "accessibility",
    label: "Accessibility",
    description: "Accessible rooms / elevator / ADA features.",
    category: "building",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["accessible", "elevatorAccess", "isAccessible"],
    defaultImportance: 0,
    explanations: {
      positive: "Accessibility features available",
      negative: "Accessibility features not listed",
      unknown: "Accessibility information is unknown",
    },
  },
  {
    id: "proximityAcademic",
    label: "Near classes",
    description: "Proximity to academic buildings / classrooms.",
    category: "location",
    controlType: "importance",
    scoringMode: "proximity",
    supportsHardConstraint: false,
    evidenceFields: ["classroomDistanceMeters", "academicDistanceMeters"],
    defaultImportance: 2,
    explanations: {
      positive: "Close to academic buildings",
      negative: "Farther from classes",
      unknown: "Distance to classes is unknown",
    },
  },
  {
    id: "proximityDining",
    label: "Near dining",
    description: "Proximity to dining halls.",
    category: "location",
    controlType: "importance",
    scoringMode: "proximity",
    supportsHardConstraint: false,
    evidenceFields: ["diningDistanceMeters"],
    defaultImportance: 2,
    explanations: {
      positive: "Close to dining",
      negative: "Farther from dining",
      unknown: "Distance to dining is unknown",
    },
  },
  {
    id: "proximityGym",
    label: "Near gym",
    description: "Proximity to recreation / gym facilities.",
    category: "location",
    controlType: "importance",
    scoringMode: "proximity",
    supportsHardConstraint: false,
    evidenceFields: ["gymDistanceMeters"],
    defaultImportance: 1,
    explanations: {
      positive: "Close to the gym",
      negative: "Farther from the gym",
      unknown: "Distance to gym is unknown",
    },
  },
  {
    id: "proximityLibrary",
    label: "Near library",
    description: "Proximity to campus libraries.",
    category: "location",
    controlType: "importance",
    scoringMode: "proximity",
    supportsHardConstraint: false,
    evidenceFields: ["libraryDistanceMeters"],
    defaultImportance: 1,
    explanations: {
      positive: "Close to the library",
      negative: "Farther from the library",
      unknown: "Distance to library is unknown",
    },
  },
  {
    id: "proximitySocial",
    label: "Near social hubs",
    description: "Proximity to student unions / social areas.",
    category: "location",
    controlType: "importance",
    scoringMode: "proximity",
    supportsHardConstraint: false,
    evidenceFields: ["socialDistanceMeters", "campusZone"],
    defaultImportance: 1,
    explanations: {
      positive: "Close to social hubs",
      negative: "Farther from social hubs",
      unknown: "Distance to social hubs is unknown",
    },
  },
  {
    id: "proximityParking",
    label: "Near parking",
    description: "Proximity to parking.",
    category: "location",
    controlType: "importance",
    scoringMode: "proximity",
    supportsHardConstraint: false,
    evidenceFields: ["parkingDistanceMeters"],
    defaultImportance: 0,
    explanations: {
      positive: "Close to parking",
      negative: "Farther from parking",
      unknown: "Distance to parking is unknown",
    },
  },
  {
    id: "walkability",
    label: "Walkability",
    description: "Overall walkability on campus from this hall.",
    category: "location",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["walkabilityRating"],
    defaultImportance: 1,
    explanations: {
      positive: "Highly walkable location",
      negative: "Less walkable location",
      unknown: "Walkability is unknown",
    },
  },
  {
    id: "location",
    label: "Overall location",
    description: "Composite campus location convenience.",
    category: "location",
    controlType: "importance",
    scoringMode: "proximity",
    supportsHardConstraint: false,
    evidenceFields: [
      "diningDistanceMeters",
      "classroomDistanceMeters",
      "gymDistanceMeters",
    ],
    defaultImportance: 2,
    explanations: {
      positive: "Convenient campus location",
      negative: "Less convenient location",
      unknown: "Location distances are unknown",
    },
  },
  {
    id: "affordability",
    label: "Affordability",
    description: "Lower yearly cost is better.",
    category: "cost",
    controlType: "importance",
    scoringMode: "cost",
    supportsHardConstraint: true,
    evidenceFields: ["yearlyCost", "semesterCost"],
    defaultImportance: 2,
    explanations: {
      positive: "More affordable relative to peers",
      negative: "Higher cost relative to peers",
      unknown: "Cost is unknown",
    },
  },
  {
    id: "value",
    label: "Value",
    description: "Quality relative to cost.",
    category: "cost",
    controlType: "importance",
    scoringMode: "cost",
    supportsHardConstraint: false,
    evidenceFields: ["yearlyCost", "collegeAvgCost", "overallSatisfaction"],
    defaultImportance: 2,
    explanations: {
      positive: "Strong value for the cost",
      negative: "Weaker value for the cost",
      unknown: "Value cannot be assessed without cost/quality data",
    },
  },
  {
    id: "buildingSizeSmall",
    label: "Smaller building",
    description: "Preference for smaller residence halls.",
    category: "building",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["buildingCapacity", "residentCount"],
    defaultImportance: 0,
    explanations: {
      positive: "Smaller building size",
      negative: "Larger building than preferred",
      unknown: "Building size is unknown",
    },
  },
  {
    id: "buildingSizeLarge",
    label: "Larger building",
    description: "Preference for larger residence halls.",
    category: "building",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["buildingCapacity", "residentCount"],
    defaultImportance: 0,
    explanations: {
      positive: "Larger building size",
      negative: "Smaller building than preferred",
      unknown: "Building size is unknown",
    },
  },
  {
    id: "elevator",
    label: "Elevator",
    description: "Building has elevator access.",
    category: "building",
    controlType: "requirement",
    scoringMode: "boolean_match",
    supportsHardConstraint: true,
    evidenceFields: ["elevatorAccess"],
    defaultImportance: 0,
    explanations: {
      positive: "Has elevator access",
      negative: "No elevator listed",
      unknown: "Elevator access is unknown",
    },
  },
  {
    id: "traditionalDormExperience",
    label: "Traditional dorm experience",
    description: "Classic residence-hall community experience.",
    category: "atmosphere",
    controlType: "importance",
    scoringMode: "categorical",
    supportsHardConstraint: false,
    evidenceFields: ["dormType", "bathroomStyle"],
    preferredCategories: ["RESIDENCE_HALL", "residence_hall", "FRESHMAN_ONLY", "MIXED"],
    defaultImportance: 0,
    explanations: {
      positive: "Traditional dorm experience",
      negative: "Less of a traditional dorm setup",
      unknown: "Housing style is unknown",
    },
  },
  {
    id: "apartmentIndependence",
    label: "Apartment independence",
    description: "Independent living with kitchen / apartment features.",
    category: "building",
    controlType: "importance",
    scoringMode: "boolean_match",
    supportsHardConstraint: false,
    evidenceFields: ["dormType", "kitchenAccess"],
    defaultImportance: 0,
    explanations: {
      positive: "Supports independent apartment-style living",
      negative: "Less independent living setup",
      unknown: "Independence features are unknown",
    },
  },
  {
    id: "overallSatisfaction",
    label: "Overall satisfaction",
    description: "Aggregate student satisfaction / overall score.",
    category: "overall",
    controlType: "importance",
    scoringMode: "quality",
    supportsHardConstraint: false,
    evidenceFields: ["overallSatisfaction", "overallScore"],
    defaultImportance: 2,
    explanations: {
      positive: "High overall satisfaction",
      negative: "Lower overall satisfaction",
      unknown: "Overall satisfaction is unknown",
    },
  },
] as const;

export type PreferenceDimensionId = (typeof PREFERENCE_DIMENSIONS)[number]["id"];

const BY_ID: Map<string, PreferenceDimensionDef> = new Map(
  PREFERENCE_DIMENSIONS.map((d) => [d.id, d])
);

export function getPreferenceDimension(id: string): PreferenceDimensionDef | undefined {
  return BY_ID.get(id);
}

export function listPreferenceDimensions(): PreferenceDimensionDef[] {
  return [...PREFERENCE_DIMENSIONS];
}

export function listPreferencesByCategory(
  category: PreferenceDimensionDef["category"]
): PreferenceDimensionDef[] {
  return PREFERENCE_DIMENSIONS.filter((d) => d.category === category);
}

export function defaultPreferenceWeights(): Record<string, number> {
  const weights: Record<string, number> = {};
  for (const dim of PREFERENCE_DIMENSIONS) {
    weights[dim.id] = dim.defaultImportance;
  }
  return weights;
}

export function emptyHardConstraints(): import("../types").HardConstraints {
  return {};
}
